/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blackjack;

/**
 *
 * @author Santosh
 */
public class GamePage extends javax.swing.JFrame {

    /**
     * Creates new form GamePage
     */
    Deck d = new Deck();
    int uservalue1  =  0;
    String userCard1 = "";
    int uservalue2  =  0;
    String userCard2 = "";
    int dealervalue1  =  0;
    String dealerCard1 = "";
    int dealervalue2  =  0;
    String dealerCard2 = "";
    int hitCard1 = 0;
    int hitCard2 = 0;
    int hitCard3 = 0;
    int standCard1 = 0;
    int standCard2 = 0;
    int standCard3 = 0;
    int bet =0;
    int counter = 0;
    int count = 0;
    int userSum =0;
    int dealerSum = 0;
    int dealerWin = 0;
    int userWin = 0;
    int loopCount = 0;
    
    public GamePage(String msg) {
        initComponents();
        jLabel2.setText("Welcome "+msg);  
        d.shuffle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 340, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/b1fv.png"))); // NOI18N
        jLabel3.setText("Deck");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 100));

        jButton1.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Deal Deck");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/b1fv.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 70, 100));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/b1fv.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 70, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/b1fv.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 70, -1));

        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 50, -1));

        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("5");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 50, -1));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Dealer");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 80, 30));

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Player");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 70, -1));

        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("10");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 50, -1));

        jButton5.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 0, 0));
        jButton5.setText("Hit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, -1, -1));

        jButton6.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 0, 0));
        jButton6.setText("Stand");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 80, -1));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 80, 100));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 80, 100));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 80, 100));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 236, 170, 30));

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 160, 30));

        jButton7.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 0));
        jButton7.setText("next");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, -1, -1));

        jButton8.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 0, 0));
        jButton8.setText("quit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, -1, -1));

        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("Select bet: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel15.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("Select Choice: ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 80, 100));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 80, 100));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 80, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/Player Interface.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        dealervalue1  =  d.deckOfCards.get(0).getValue();
        dealerSum = dealerSum + dealervalue1;
       dealerCard1 = d.deckOfCards.get(0).getImage();
       jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/"+dealerCard1+".png")));
       
       jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/b1fv.png")));
        
       uservalue1  =  d.deckOfCards.get(2).getValue();
       userCard1 = d.deckOfCards.get(2).getImage();
       jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/"+userCard1+".png")));
       userSum = userSum + uservalue1;
       uservalue2  =  d.deckOfCards.get(3).getValue();
       userCard2 = d.deckOfCards.get(3).getImage();
       jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/"+userCard2+".png")));
       userSum = userSum + uservalue2;
       counter = 2;
       count = 1;  
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        bet = 1;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/b1fv.png")));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/b1fv.png")));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/b1fv.png")));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/b1fv.png")));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        
        bet = 0;
        jLabel12.setText(null);
        jLabel13.setText(null);
        d.shuffle();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String msg = "";
        if(userWin == dealerWin)
        {
            msg = "Congrats! Game Tied";
        }
        else if(userWin > dealerWin)
        {
            msg = "You Won!!!";
        }
        else
            msg  = "You Lose!!!";
        
        ResultPage rp = new ResultPage(msg);
        rp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        bet = 5;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        bet = 10;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        counter++;
        if(counter == 3)   
        {
            hitCard1 = d.deckOfCards.get(4).getValue();
            jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/"+d.deckOfCards.get(4).getImage()+".png")));
            userSum = userSum + hitCard1;
        }
        else if(counter == 4)
        {
            hitCard2 = d.deckOfCards.get(5).getValue();
            jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/"+d.deckOfCards.get(5).getImage()+".png")));
            userSum = userSum + hitCard2;
        }            
        else
        {  
            hitCard3 = d.deckOfCards.get(6).getValue();
            jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/"+d.deckOfCards.get(6).getImage()+".png")));
            userSum = userSum + hitCard3;
        }
        
        if(userSum == 21)
       {
           userWin++;
           jLabel13.setText("BlackJack! you win: "+(2*bet));
       }
        
        if(dealerSum >=21 || userSum >=21)
        {
            if(dealerSum == 21)
            {
                dealerWin++;
                jLabel12.setText("BlackJack! you win: "+(2*bet));
            }
            else if(userSum == 21)
            {
                userWin++;
                jLabel13.setText("BlackJack! you win: "+(2*bet));
            }
            else if(dealerSum<userSum)
            {
                dealerWin++;
                jLabel12.setText("you win: "+(2*bet));
            }
            else if(dealerSum > userSum)
            {
                userWin++;
                jLabel13.setText("you win: "+(2*bet));
            }
        }
        
        
          
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        count++;
        if(count == 2)   
        {
            dealervalue2  =  d.deckOfCards.get(1).getValue();
            dealerCard2 = d.deckOfCards.get(1).getImage();
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/"+dealerCard2+".png")));
            dealerSum = dealerSum + dealervalue2;
        }
        else if(count == 3)
        {
            standCard1 = d.deckOfCards.get(7).getValue();
            jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/"+d.deckOfCards.get(7).getImage()+".png")));
            dealerSum = dealerSum + standCard1;
        }            
        else if(count == 4)
        {
            standCard2 = d.deckOfCards.get(8).getValue();
            jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/"+d.deckOfCards.get(8).getImage()+".png")));
            dealerSum = dealerSum + standCard2;
        }
        else
        {
            standCard3 = d.deckOfCards.get(9).getValue();
            jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/images/"+d.deckOfCards.get(9).getImage()+".png")));
            dealerSum = dealerSum + standCard3;
        }
        
        if(dealerSum == 21)
        {
            dealerWin++;
            jLabel12.setText("BlackJack! you win: "+(2*bet));
        }
        
        if(dealerSum >=21 || userSum >=21)
        {            
            if(userSum == 21)
            {
                userWin++;
                jLabel13.setText("BlackJack! you win: "+(2*bet));
            }
            else if(dealerSum<userSum)
            {
                dealerWin++;
                jLabel12.setText("you win: "+(2*bet));
            }
            else if(dealerSum > userSum)
            {
                userWin++;
                jLabel13.setText("you win: "+(2*bet));
            } 
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePage("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
